language: ruby
cache: bundler
before_script:
  - psql -c 'create database ruby_au_test;' -U postgres >/dev/null
  - bundle exec rake db:create db:schema:load
  - yarn install
  - bundle exec rails webpacker:compile
script:
  - bundle exec rspec
  - bundle exec rubocop
services:
  - postgresql
